// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: findcar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Findcar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Movies []string `protobuf:"bytes,2,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *Findcar) Reset() {
	*x = Findcar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Findcar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Findcar) ProtoMessage() {}

func (x *Findcar) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Findcar.ProtoReflect.Descriptor instead.
func (*Findcar) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{0}
}

func (x *Findcar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Findcar) GetMovies() []string {
	if x != nil {
		return x.Movies
	}
	return nil
}

type CreateFindcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Findcar *Findcar `protobuf:"bytes,1,opt,name=findcar,proto3" json:"findcar,omitempty"`
}

func (x *CreateFindcarRequest) Reset() {
	*x = CreateFindcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFindcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFindcarRequest) ProtoMessage() {}

func (x *CreateFindcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFindcarRequest.ProtoReflect.Descriptor instead.
func (*CreateFindcarRequest) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFindcarRequest) GetFindcar() *Findcar {
	if x != nil {
		return x.Findcar
	}
	return nil
}

type CreateFindcarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Findcar *Findcar `protobuf:"bytes,1,opt,name=findcar,proto3" json:"findcar,omitempty"`
}

func (x *CreateFindcarResponse) Reset() {
	*x = CreateFindcarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFindcarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFindcarResponse) ProtoMessage() {}

func (x *CreateFindcarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFindcarResponse.ProtoReflect.Descriptor instead.
func (*CreateFindcarResponse) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFindcarResponse) GetFindcar() *Findcar {
	if x != nil {
		return x.Findcar
	}
	return nil
}

type ReadFindcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarName string `protobuf:"bytes,1,opt,name=car_name,json=carName,proto3" json:"car_name,omitempty"`
}

func (x *ReadFindcarRequest) Reset() {
	*x = ReadFindcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFindcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFindcarRequest) ProtoMessage() {}

func (x *ReadFindcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFindcarRequest.ProtoReflect.Descriptor instead.
func (*ReadFindcarRequest) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFindcarRequest) GetCarName() string {
	if x != nil {
		return x.CarName
	}
	return ""
}

type ReadFindcarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Findcar *Findcar `protobuf:"bytes,1,opt,name=findcar,proto3" json:"findcar,omitempty"`
}

func (x *ReadFindcarResponse) Reset() {
	*x = ReadFindcarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFindcarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFindcarResponse) ProtoMessage() {}

func (x *ReadFindcarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFindcarResponse.ProtoReflect.Descriptor instead.
func (*ReadFindcarResponse) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFindcarResponse) GetFindcar() *Findcar {
	if x != nil {
		return x.Findcar
	}
	return nil
}

type UpdateFindcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Findcar *Findcar `protobuf:"bytes,1,opt,name=findcar,proto3" json:"findcar,omitempty"`
}

func (x *UpdateFindcarRequest) Reset() {
	*x = UpdateFindcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFindcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFindcarRequest) ProtoMessage() {}

func (x *UpdateFindcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFindcarRequest.ProtoReflect.Descriptor instead.
func (*UpdateFindcarRequest) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFindcarRequest) GetFindcar() *Findcar {
	if x != nil {
		return x.Findcar
	}
	return nil
}

type UpdateFindcarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Findcar *Findcar `protobuf:"bytes,1,opt,name=findcar,proto3" json:"findcar,omitempty"`
}

func (x *UpdateFindcarResponse) Reset() {
	*x = UpdateFindcarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFindcarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFindcarResponse) ProtoMessage() {}

func (x *UpdateFindcarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFindcarResponse.ProtoReflect.Descriptor instead.
func (*UpdateFindcarResponse) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFindcarResponse) GetFindcar() *Findcar {
	if x != nil {
		return x.Findcar
	}
	return nil
}

type DeleteFindcarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarName string `protobuf:"bytes,1,opt,name=car_name,json=carName,proto3" json:"car_name,omitempty"`
}

func (x *DeleteFindcarRequest) Reset() {
	*x = DeleteFindcarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFindcarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFindcarRequest) ProtoMessage() {}

func (x *DeleteFindcarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFindcarRequest.ProtoReflect.Descriptor instead.
func (*DeleteFindcarRequest) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFindcarRequest) GetCarName() string {
	if x != nil {
		return x.CarName
	}
	return ""
}

type DeleteFindcarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarName string `protobuf:"bytes,1,opt,name=car_name,json=carName,proto3" json:"car_name,omitempty"`
}

func (x *DeleteFindcarResponse) Reset() {
	*x = DeleteFindcarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_findcar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFindcarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFindcarResponse) ProtoMessage() {}

func (x *DeleteFindcarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findcar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFindcarResponse.ProtoReflect.Descriptor instead.
func (*DeleteFindcarResponse) Descriptor() ([]byte, []int) {
	return file_findcar_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFindcarResponse) GetCarName() string {
	if x != nil {
		return x.CarName
	}
	return ""
}

var File_findcar_proto protoreflect.FileDescriptor

var file_findcar_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x22, 0x35, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64,
	0x63, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x22,
	0x42, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x63,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63,
	0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64,
	0x63, 0x61, 0x72, 0x22, 0x43, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07,
	0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52,
	0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x22, 0x2f, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64,
	0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x13, 0x52, 0x65, 0x61,
	0x64, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x63, 0x61, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x22, 0x42, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72,
	0x22, 0x43, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x07, 0x66, 0x69,
	0x6e, 0x64, 0x63, 0x61, 0x72, 0x22, 0x31, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xca, 0x02, 0x0a,
	0x0e, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72,
	0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x12, 0x1b,
	0x2e, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x69,
	0x6e, 0x64, 0x63, 0x61, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x69, 0x6e, 0x64,
	0x63, 0x61, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x12, 0x1d, 0x2e, 0x66, 0x69, 0x6e,
	0x64, 0x63, 0x61, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x69, 0x6e, 0x64,
	0x63, 0x61, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x63, 0x61, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_findcar_proto_rawDescOnce sync.Once
	file_findcar_proto_rawDescData = file_findcar_proto_rawDesc
)

func file_findcar_proto_rawDescGZIP() []byte {
	file_findcar_proto_rawDescOnce.Do(func() {
		file_findcar_proto_rawDescData = protoimpl.X.CompressGZIP(file_findcar_proto_rawDescData)
	})
	return file_findcar_proto_rawDescData
}

var file_findcar_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_findcar_proto_goTypes = []interface{}{
	(*Findcar)(nil),               // 0: findcar.Findcar
	(*CreateFindcarRequest)(nil),  // 1: findcar.CreateFindcarRequest
	(*CreateFindcarResponse)(nil), // 2: findcar.CreateFindcarResponse
	(*ReadFindcarRequest)(nil),    // 3: findcar.ReadFindcarRequest
	(*ReadFindcarResponse)(nil),   // 4: findcar.ReadFindcarResponse
	(*UpdateFindcarRequest)(nil),  // 5: findcar.UpdateFindcarRequest
	(*UpdateFindcarResponse)(nil), // 6: findcar.UpdateFindcarResponse
	(*DeleteFindcarRequest)(nil),  // 7: findcar.DeleteFindcarRequest
	(*DeleteFindcarResponse)(nil), // 8: findcar.DeleteFindcarResponse
}
var file_findcar_proto_depIdxs = []int32{
	0, // 0: findcar.CreateFindcarRequest.findcar:type_name -> findcar.Findcar
	0, // 1: findcar.CreateFindcarResponse.findcar:type_name -> findcar.Findcar
	0, // 2: findcar.ReadFindcarResponse.findcar:type_name -> findcar.Findcar
	0, // 3: findcar.UpdateFindcarRequest.findcar:type_name -> findcar.Findcar
	0, // 4: findcar.UpdateFindcarResponse.findcar:type_name -> findcar.Findcar
	1, // 5: findcar.FindcarService.CreateFindcar:input_type -> findcar.CreateFindcarRequest
	3, // 6: findcar.FindcarService.ReadFindcar:input_type -> findcar.ReadFindcarRequest
	5, // 7: findcar.FindcarService.UpdateFindcar:input_type -> findcar.UpdateFindcarRequest
	7, // 8: findcar.FindcarService.DeleteFindcar:input_type -> findcar.DeleteFindcarRequest
	2, // 9: findcar.FindcarService.CreateFindcar:output_type -> findcar.CreateFindcarResponse
	4, // 10: findcar.FindcarService.ReadFindcar:output_type -> findcar.ReadFindcarResponse
	6, // 11: findcar.FindcarService.UpdateFindcar:output_type -> findcar.UpdateFindcarResponse
	8, // 12: findcar.FindcarService.DeleteFindcar:output_type -> findcar.DeleteFindcarResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_findcar_proto_init() }
func file_findcar_proto_init() {
	if File_findcar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_findcar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Findcar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFindcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFindcarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFindcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFindcarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFindcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFindcarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFindcarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_findcar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFindcarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_findcar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findcar_proto_goTypes,
		DependencyIndexes: file_findcar_proto_depIdxs,
		MessageInfos:      file_findcar_proto_msgTypes,
	}.Build()
	File_findcar_proto = out.File
	file_findcar_proto_rawDesc = nil
	file_findcar_proto_goTypes = nil
	file_findcar_proto_depIdxs = nil
}
